website/views.py
from flask import Blueprint, render_template, request, url_for, flash, jsonify, redirect
from flask_login import login_required, current_user
from .models import ContactUs, User, WatchlistItem
from . import db
import json
import pandas as pd
import yfinance as yf
from pypfopt import EfficientFrontier, risk_models, expected_returns
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices
from datetime import timedelta

# from my_module import my_function
import sys
from pathlib import Path

# Add the current directory to the Python import paths
current_directory = Path(__file__).resolve().parent
sys.path.append(str(current_directory))
from portfolio import get_stock_data, optimize_portfolio

# Import your function
# from my_module import generate_portfolio

views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
def index():
    if current_user.is_authenticated:
        return redirect(url_for("views.dashboard"))
    return render_template("index.html", user=current_user)


@views.route("/logged", methods=["GET"])
@login_required
def dashboard():
    return render_template("watchlist.html", user=current_user)


@views.route("/graph", methods=["GET", "POST"])
@login_required
def graph():
    return render_template("graph.html", user=current_user)


@views.route("/", methods=["GET", "POST"])
def home():
    return render_template("index.html", user=current_user)


nifty50_tickers = [
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "APOLLOHOSP.NS",
    "ASIANPAINT.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "BPCL.NS",
    "BHARTIARTL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "HDFC.NS",
    "ICICIBANK.NS",
    "ITC.NS",
    "INDUSINDBK.NS",
    "INFY.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NTPC.NS",
    "NESTLEIND.NS",
    "ONGC.NS",
    "POWERGRID.NS",
    "RELIANCE.NS",
    "SBILIFE.NS",
    "SBIN.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "UPL.NS",
    "ULTRACEMCO.NS",
    "WIPRO.NS",
]

niftymidcap = [
    "ABB.NS",
    "AUBANK.NS",
    "ABBOTINDIA.NS",
    "ALKEM.NS",
    "ASHOKLEY.NS",
    "ASTRAL.NS",
    "AUROPHARMA.NS",
    "BALKRISIND.NS",
    "BATAINDIA.NS",
    "BHARATFORG.NS",
    "CANBK.NS",
    "COFORGE.NS",
    "CONCOR.NS",
    "CUMMINSIND.NS",
    "ESCORTS.NS",
    "FEDERALBNK.NS",
    "GODREJPROP.NS",
    "GUJGASLTD.NS",
    "HINDPETRO.NS",
    "HONAUT.NS",
    "IDFCFIRSTB.NS",
    "INDHOTEL.NS",
    "JINDALSTEL.NS",
    "JUBLFOOD.NS",
    "LTTS.NS",
    "LICHSGFIN.NS",
    "LUPIN.NS",
    "MRF.NS",
    "M&MFIN.NS",
    "MFSL.NS",
    "OBEROIRLTY.NS",
    "OFSS.NS",
    "PAGEIND.NS",
    "PERSISTENT.NS",
    "PETRONET.NS",
    "POLYCAB.NS",
    "PFC.NS",
    "PNB.NS",
    "RECLTD.NS",
    # "SRTRANSFIN.NS",
    "SAIL.NS",
    "TVSMOTOR.NS",
    "TATACOMM.NS",
    "TORNTPOWER.NS",
    "TRENT.NS",
    "UBL.NS",
    "IDEA.NS",
    "VOLTAS.NS",
    "ZEEL.NS",
    "ZYDUSLIFE.NS",
]


@views.route("/portfolio", methods=["GET", "POST"])
def portfolio():
    if request.method == "POST":
        investment_amount = float(request.form["investment_amount"])
        risk_preference = request.form["risk_preference"]
        stock_data = get_stock_data(nifty50_tickers, niftymidcap, risk_preference)
        allocation, leftover = optimize_portfolio(stock_data, investment_amount)
        return render_template(
            "result.html", allocation=allocation, leftover=leftover, user=current_user
        )
    return render_template("portfolio.html", user=current_user)


@views.route("/pricing", methods=["GET", "POST"])
def pricing():
    return render_template("pricing.html", user=current_user)


@views.route("/stock_analysis", methods=["GET", "POST"])
def stock_analysis():
    if request.method == "POST":
        symbol = request.form.get("symbol")
        return render_template("stock_analysis.html", symbol=symbol, user=current_user)
    return render_template("stock_analysis_form.html", user=current_user)


@views.route("/contact", methods=["GET", "POST"])
def contact():
    return render_template("contact.html", user=current_user)


@views.route("/about", methods=["GET", "POST"])
def about():
    return render_template("AboutUs.html", user=current_user)


# @views.route("/search", methods=["GET"])
# def search_stocks():
#     search_query = request.args.get("q")
#     if search_query:
#         stock = yf.Ticker(f"{search_query}.NS")
#         if stock.info:
#             stock_info = {
#                 "symbol": stock.info["symbol"],
#                 "name": stock.info["longName"],
#                 "price": round(stock.info["regularMarketPrice"], 2),
#                 "change": round(stock.info["regularMarketChange"], 2),
#                 "percent_change": round(stock.info["regularMarketChangePercent"], 2),
#             }
#             return render_template("search.html", stock_info=stock_info)
#         else:
#             return render_template("search.html", error="Unable to fetch stock data.")
#     else:
#         return render_template("search.html", error="Missing search query.")


@views.route("/search", methods=["GET", "POST"])
def search():
    if request.method == "POST":
        symbol = request.form["symbol"]
        ticker = yf.Ticker(symbol)
        if ticker.info:
            return render_template("search_results.html", symbol=symbol)
        else:
            return render_template("search.html", error="Invalid symbol")
    else:
        return render_template("search.html")


@views.route("/search_results")
def search_results():
    symbol = request.args.get("symbol")
    ticker = yf.Ticker(symbol)
    info = ticker.info
    return render_template("search_results.html", symbol=symbol, info=info)


@views.route("/add_stock_to_watchlist", methods=["POST"])
@login_required
def add_stock_to_watchlist():
    stock_symbol = request.form.get("stock_symbol")
    if not stock_symbol:
        flash("Stock symbol cannot be empty.", category="error")
    else:
        new_watchlist_item = WatchlistItem(
            stock_symbol=stock_symbol, user_id=current_user.id
        )
        db.session.add(new_watchlist_item)
        db.session.commit()
        flash("Stock added to watchlist!", category="success")
    return redirect(url_for("views.view_watchlist"))


def get_stock_price_data(stock_symbol):
    stock = yf.Ticker(stock_symbol)
    history = stock.history(period="6mo")
    return history


def calculate_percentage_change(current_price, past_price):
    change = ((current_price - past_price) / past_price) * 100
    return round(change, 2)


@views.route("/view_watchlist")
@login_required
def view_watchlist():
    user_watchlist = WatchlistItem.query.filter_by(user_id=current_user.id).all()
    stock_data = []

    for watchlist_item in user_watchlist:
        stock_history = get_stock_price_data(watchlist_item.stock_symbol)
        latest_price = stock_history.iloc[-1]["Close"]
        day_change = calculate_percentage_change(
            latest_price, stock_history.iloc[-2]["Close"]
        )
        week_change = calculate_percentage_change(
            latest_price, stock_history.iloc[-6]["Close"]
        )
        month_change = calculate_percentage_change(
            latest_price, stock_history.iloc[-21]["Close"]
        )
        six_month_change = calculate_percentage_change(
            latest_price, stock_history.iloc[0]["Close"]
        )

        stock_data.append(
            {
                "id": watchlist_item.id,
                "symbol": watchlist_item.stock_symbol,
                "latest_price": latest_price,
                "day_change": day_change,
                "week_change": week_change,
                "month_change": month_change,
                "six_month_change": six_month_change,
            }
        )

    return render_template("watchlist.html", user=current_user, stock_data=stock_data)


@views.route("/remove_stock_from_watchlist/<int:watchlist_item_id>")
@login_required
def remove_stock_from_watchlist(watchlist_item_id):
    watchlist_item = WatchlistItem.query.get(watchlist_item_id)
    if watchlist_item:
        if watchlist_item.user_id == current_user.id:
            db.session.delete(watchlist_item)
            db.session.commit()
            flash("Stock removed from watchlist.", category="success")
        else:
            flash(
                "You do not have permission to remove this stock from the watchlist.",
                category="error",
            )
    else:
        flash("Stock not found in watchlist.", category="error")
    return redirect(url_for("views.view_watchlist"))

website/templates/AboutUs.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/markets/indices/" rel="noopener"
            target="_blank"><span class="blue-text">Indices</span></a> <span class="blue-text">and</span> <a
            href="https://www.tradingview.com/markets/currencies/" rel="noopener" target="_blank"><span
                class="blue-text">Forex</span></a> by TradingView</div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-market-overview.js"
        async>
            {
                "colorTheme": "dark",
                    "dateRange": "1D",
                        "showChart": true,
                            "locale": "en",
                                "largeChartUrl": "",
                                    "isTransparent": true,
                                        "showSymbolLogo": true,
                                            "showFloatingTooltip": true,
                                                "width": "400",
                                                    "height": "660",
                                                        "plotLineColorGrowing": "rgba(41, 98, 255, 1)",
                                                            "plotLineColorFalling": "rgba(41, 98, 255, 1)",
                                                                "gridLineColor": "rgba(240, 243, 250, 0)",
                                                                    "scaleFontColor": "rgba(106, 109, 120, 1)",
                                                                        "belowLineFillColorGrowing": "rgba(41, 98, 255, 0.12)",
                                                                            "belowLineFillColorFalling": "rgba(41, 98, 255, 0.12)",
                                                                                "belowLineFillColorGrowingBottom": "rgba(41, 98, 255, 0)",
                                                                                    "belowLineFillColorFallingBottom": "rgba(41, 98, 255, 0)",
                                                                                        "symbolActiveColor": "rgba(41, 98, 255, 0.12)",
                                                                                            "tabs": [
                                                                                                {
                                                                                                    "title": "Indices",
                                                                                                    "symbols": [
                                                                                                        {
                                                                                                            "s": "FOREXCOM:SPXUSD",
                                                                                                            "d": "S&P 500"
                                                                                                        },
                                                                                                        {
                                                                                                            "s": "NSE:NIFTY",
                                                                                                            "d": "Nifty 50"
                                                                                                        },
                                                                                                        {
                                                                                                            "s": "BSE:SENSEX",
                                                                                                            "d": "Sensex"
                                                                                                        }
                                                                                                    ],
                                                                                                    "originalTitle": "Indices"
                                                                                                },
                                                                                                {
                                                                                                    "title": "Forex",
                                                                                                    "symbols": [
                                                                                                        {
                                                                                                            "s": "FX_IDC:USDINR",
                                                                                                            "d": "USD INR"
                                                                                                        }
                                                                                                    ],
                                                                                                    "originalTitle": "Forex"
                                                                                                }
                                                                                            ]
            }
        </script>
</div>
<!-- TradingView Widget END -->
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>equifolio.ai</title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../static/style.css">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
</head>

<body>

  <div class="main">
    <div class="navbar">
      <div class="icon">
        <a href="{{ url_for('views.home')}}"><img src="../static/logo_.png" alt="logo" class="logo" width="120px"
            style='vertical-align:middle;'></a>
        </a>
      </div>

      <div class="menu">
        <ul>
          <li><a href="{{ url_for('views.home')}}">HOME</a></li>
          <li><a href="{{ url_for('views.portfolio')}}">Portfolio</a></li>
          <li><a href="{{ url_for('views.pricing')}}">Pricing</a></li>
          <li><a href="{{ url_for('views.stock_analysis')}}">Stocks</a></li>
          <li><a href="{{ url_for('views.contact')}}">CONTACT</a></li>
          <li><a href="{{ url_for('views.about')}}">About Us</a></li>
          {% if user.is_authenticated %}
          <li><a href="{{ url_for('views.view_watchlist')}}">Watchlist</a></li>
          <li><a class="nav-item nav-link" id="logout" href="/logout">Logout</a></li>
          {% endif %}
        </ul>
      </div>



    </div>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>


</body>
{% block widget %}{% endblock %}
<style>
  .tradingview-widget-container {
    position: fixed;
    /* Change the values below according to your preference */
    top: 10px;
    right: 10px;
    z-index: 9999;
    /* To keep the widget on top of other elements */
  }
</style>

</html>

website/templates/graph.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="technical-analysis-chart-demo"></div>
  <div class="tradingview-widget-copyright"><a href="https://www.tradingview.com/symbols/AAPL/" rel="noopener"
      target="_blank"><span class="blue-text">AAPL stock chart</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
    new TradingView.widget(
      {
        "container_id": "technical-analysis-chart-demo",
        "width": "100%",
        "height": "100%",
        "autosize": true,
        "symbol": "HDFCBANK",
        "interval": "D",
        "timezone": "exchange",
        "theme": "light",
        "style": "1",
        "toolbar_bg": "#f1f3f6",
        "withdateranges": true,
        "hide_side_toolbar": false,
        "allow_symbol_change": true,
        "save_image": false,
        "studies": [
          "ROC@tv-basicstudies",
          "StochasticRSI@tv-basicstudies",
          "MASimple@tv-basicstudies"
        ],
        "show_popup_button": true,
        "popup_width": "1000",
        "popup_height": "650",
        "locale": "en"
      }
    );
  </script>
</div>
<!-- TradingView Widget END -->
{% endblock %}

website/templates/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
        <div class="content">
          <div  style="width: 50%">
            <h1>Invest in your future with Equifolio.ai</h1>
            <p class="par" >
              Invest in your future with Equifolio.ai! Our AI-powered platform creates personalized stock portfolios for long-term investment based on your risk tolerance and goals. Diversify your portfolio and access a range of assets you might not have been able to before. Get real-time updates and insights to make informed investment decisions. Start investing with confidence today!
            </p>
          </div>
                <button class="cn"><a href="#">JOIN US</a></button>
                <div class="form">
                  <form method="POST" action="/login">
                    <h3 align="center">Login</h3>
                    <br>
                    <div class="form-group">
                      <label for="email">Email Address</label>
                      <input
                        type="email"
                        class="form-control"
                        id="email"
                        name="email"
                        placeholder="Enter email"
                      />
                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                      <label for="password">Password</label>
                      <input
                        type="password"
                        class="form-control"
                        id="password"
                        name="password"
                        placeholder="Enter password"
                      />
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary">Login</button>
                    <!-- sign up -->
                    <br>
                    <br>
                   <p>Not a user? <a href="/sign-up"style="color: #fff;">Sign Up</a></p>
                  </form>
                  </div>
                    </div>
                </div>
        </div>
    </div>
  {% endblock %}

website/templates/manam.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Portfolio Optimizer</title>
</head>

<body>
    <h1>Portfolio Optimizer</h1>
    <form method="POST" action="/manam">
        <label for="investment_amount">Investment Amount:</label>
        <input type="number" id="investment_amount" name="investment_amount" step="any" required>
        <input type="submit" value="Optimize Portfolio">
    </form>
</body>

</html>

website/templates/navbar.html
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>

    <div class="py-10">
        <nav class="relative px-4 py-4 flex justify-between items-center border-y border-gray-400 dark:border-gray-700">
            <a class="text-3xl font-bold leading-none" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#4F46E5" class="w-8 h-8">
                    <path fill-rule="evenodd"
                        d="M9.315 7.584C12.195 3.883 16.695 1.5 21.75 1.5a.75.75 0 01.75.75c0 5.056-2.383 9.555-6.084 12.436A6.75 6.75 0 019.75 22.5a.75.75 0 01-.75-.75v-4.131A15.838 15.838 0 016.382 15H2.25a.75.75 0 01-.75-.75 6.75 6.75 0 017.815-6.666zM15 6.75a2.25 2.25 0 100 4.5 2.25 2.25 0 000-4.5z"
                        clip-rule="evenodd"></path>
                    <path
                        d="M5.26 17.242a.75.75 0 10-.897-1.203 5.243 5.243 0 00-2.05 5.022.75.75 0 00.625.627 5.243 5.243 0 005.022-2.051.75.75 0 10-1.202-.897 3.744 3.744 0 01-3.008 1.51c0-1.23.592-2.323 1.51-3.008z">
                    </path>
                </svg>
            </a>
            <div class="lg:hidden">
                <button class="navbar-burger flex items-center text-gray-600 dark:text-gray-300 p-3">
                    <svg class="block h-4 w-4 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <title>Mobile menu</title>
                        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
                    </svg>
                </button>
            </div>
            <ul
                class="hidden absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 lg:flex lg:mx-auto lg:items-center lg:w-auto lg:space-x-6">
                <li>
                    <a class="text-sm text-gray-500 hover:text-gray-600 dark:text-gray-300" href="#">
                        Home
                    </a>
                </li>
                <li class="text-gray-300">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
                        class="w-4 h-4 current-fill" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z">
                        </path>
                    </svg>
                </li>
                <li>
                    <a class="text-sm text-indigo-600 font-bold" href="#">About Us</a>
                </li>
                <li class="text-gray-300">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
                        class="w-4 h-4 current-fill" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z">
                        </path>
                    </svg>
                </li>
                <li>
                    <a class="text-sm text-gray-500 hover:text-gray-600 dark:text-gray-300" href="#">
                        Services
                    </a>
                </li>
                <li class="text-gray-300">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
                        class="w-4 h-4 current-fill" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z">
                        </path>
                    </svg>
                </li>
                <li>
                    <a class="text-sm text-gray-500 hover:text-gray-600 dark:text-gray-300" href="#">
                        Pricing
                    </a>
                </li>
                <li class="text-gray-300">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor"
                        class="w-4 h-4 current-fill" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 5v0m0 7v0m0 7v0m0-13a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z">
                        </path>
                    </svg>
                </li>
                <li>
                    <a class="text-sm text-gray-500 hover:text-gray-600 dark:text-gray-300" href="#">
                        Contact
                    </a>
                </li>
            </ul>
            <div class="space-x-2 hidden lg:block">
                <button
                    class="rounded-md border border-indigo-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-indigo-600 hover:bg-indigo-500">
                    Login
                </button>
                <button
                    class="rounded-md bg-indigo-600 px-3.5 py-1.5 text-base font-semibold leading-7 text-white hover:bg-indigo-500">
                    SignUp
                </button>
            </div>
        </nav>
    </div>
</body>

</html>

website/templates/portfolio.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<div class="portfolio">
    <h1>Portfolio Optimizer</h1>
    <form class="portfolio-form">
        <label for="investment_amount">Investment Amount:</label>
        <input type="number" id="investment_amount" name="investment_amount" step="any" required>

        <label for="risk_preference">Risk Preference:</label>
        <select id="risk_preference" name="risk_preference" class="form-control" required>
            <option value="nifty50">Option 1 (Nifty50)</option>
            <option value="niftymidcap">Option 2 (Nifty Midcap)</option>
            <option value="both">Option 3 (Both Nifty50 and Nifty Midcap)</option>
        </select>

        <input class="optimize" type="submit" value="Optimize Portfolio">
    </form>
</div>
{% endblock %}

website/templates/result.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1 class="mt-4 mb-4">Optimized Portfolio</h1>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Stock</th>
                <th>Shares</th>
            </tr>
        </thead>
        <tbody>
            {% for stock, shares in allocation.items() %}
            <tr>
                <td>{{ stock }}</td>
                <td>{{ shares }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2 class="mb-3">Leftover Amount: {{ leftover }}</h2>
    <a href="/" class="btn btn-primary optimize-another">Optimize Another Portfolio</a>
</div>
{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1>Search for a Stock</h1>
    <form method="POST" action="{{ url_for('search_results') }}">
        <div class="form-group">
            <label for="symbol">Stock Symbol</label>
            <input type="text" class="form-control" id="symbol" name="symbol" required>
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>
{% endblock %}

website/templates/watchlist.html
{% extends "base.html" %}
{% block widget %}
{% include "widget.html" %}
{% endblock %}

{% block content %}
<div class="watchlist-container">
    <h1 class="watchlist-title">Watchlist</h1>
    <form class="watchlist-form" action="{{ url_for('views.add_stock_to_watchlist') }}" method="post">
        <input type="text" name="stock_symbol" placeholder="Stock Symbol">
        <button type="submit">Add Stock to Watchlist</button>
    </form>
    <table class="watchlist-table">
        <thead>
            <tr>
                <th>Symbol</th>
                <th>Latest Price</th>
                <th>Day Change</th>
                <th>Week Change</th>
                <th>Month Change</th>
                <th>Six Month Change</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for stock in stock_data %}
            <tr>
                <td class="symbol">{{ stock.symbol }}</td>
                <td class="latest-price">{{ stock.latest_price }}</td>
                <td class="change">{{ stock.day_change }}%</td>
                <td class="change">{{ stock.week_change }}%</td>
                <td class="change">{{ stock.month_change }}%</td>
                <td class="change">{{ stock.six_month_change }}%</td>
                <td><a href="{{ url_for('views.remove_stock_from_watchlist', watchlist_item_id=stock.id) }}">Remove</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}